# Generated by Django 3.2.6 on 2021-08-13 17:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('findCommonTimeToMeetApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='timingPreferences',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findCommonTimeToMeetApp.usertimingpreferences'),
        ),
        migrations.AlterField(
            model_name='usertimingpreferences',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
