# Generated by Django 3.2.6 on 2021-08-14 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findCommonTimeToMeetApp', '0003_auto_20210814_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertimingpreferences',
            name='day_end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='usertimingpreferences',
            name='day_start_time',
            field=models.TimeField(),
        ),
    ]
